modLoader="javafml"
loaderVersion="[35,]"
issueTrackerURL="https://github.com/Darkhax-Minecraft/cauldron-recipes/issues"
license="LGPL v2.1"

[[mods]]
modId="cauldronrecipes"
updateJSONURL="https://updates.blamejared.com/get?n=cauldronrecipes&gv=1.16.4"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.cauldronrecipes]]
    modId="forge"
    mandatory=true
    versionRange="[35,]"
    ordering="NONE"
    side="SERVER"

[[dependencies.cauldronrecipes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="SERVER"
	
[[dependencies.cauldronrecipes]]
    modId="bookshelf"
    mandatory=true
    versionRange="[9,)"
    ordering="AFTER"
    side="SERVER"